databases:
  - name: sims-db
    databaseName: sims_nzww
    user: sims_nzww_user
    plan: free
    region: oregon

services:
  - type: web
    name: sims-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-d9h5cafavr4c73bgftv0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: sims_nzww_user
      - key: DB_PASSWORD
        value: 6dsNzrqJqoLWp5K9zFZG4MoZMnnXRgmk
      - key: DB_DATABASE
        value: sims_nzww
      - key: JWT_SECRET
        value: sims-jwt-secret-2026-change-me
      - key: JWT_REFRESH_SECRET
        value: sims-refresh-secret-2026-change-me
      - key: CORS_ORIGIN
        value: https://sims-frontend.netlify.app
