databases:
  - name: sims-db
    databaseName: sims
    user: sims
    plan: free

services:
  - type: web
    name: sims-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: sims-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sims-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: sims-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sims-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: sims-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://sims-school.netlify.app
