import '../types/role_id.dart';

/// A single page within a dashboard.
class DashboardPage {
  final String key;
  final String label;

  const DashboardPage({required this.key, required this.label});
}

/// A dashboard definition with its pages.
class DashboardDef {
  final String key;
  final String label;
  final RoleId role;
  final List<DashboardPage> pages;

  const DashboardDef({
    required this.key,
    required this.label,
    required this.role,
    required this.pages,
  });
}

/// Full catalog of all dashboards and their pages.
/// Matches the React Native dashboardCatalog.ts exactly.
const List<DashboardDef> dashboardCatalog = [
  DashboardDef(
    key: 'Headmaster',
    label: 'Headmaster',
    role: RoleId.headmaster,
    pages: [
      DashboardPage(key: 'overview', label: 'Executive Overview'),
      DashboardPage(key: 'oversight', label: 'School-Wide Oversight'),
      DashboardPage(key: 'staff', label: 'Staff Directory & Appraisal'),
      DashboardPage(key: 'approvals', label: 'Approvals Inbox'),
      DashboardPage(key: 'reports', label: 'Reports & Analytics'),
      DashboardPage(key: 'communication', label: 'Communication'),
      DashboardPage(key: 'discipline', label: 'Discipline Case Log'),
      DashboardPage(key: 'users', label: 'User Management'),
      DashboardPage(key: 'access', label: 'Access Control'),
      DashboardPage(key: 'menu', label: "Today's Menu"),
      DashboardPage(key: 'sync', label: 'Sync & Data Health'),
    ],
  ),
  DashboardDef(
    key: 'Academic',
    label: 'Asst. Headmaster (Academic)',
    role: RoleId.asstHeadmasterAcademic,
    pages: [
      DashboardPage(key: 'overview', label: 'Academic Overview'),
      DashboardPage(key: 'monitor', label: 'Academic Monitor'),
      DashboardPage(key: 'insights', label: 'Insights & Analytics'),
      DashboardPage(key: 'timetable', label: 'Timetable Manager'),
      DashboardPage(key: 'exams', label: 'Exam Management'),
      DashboardPage(key: 'reports', label: 'Report Cards'),
      DashboardPage(key: 'transcripts', label: 'Transcripts'),
      DashboardPage(key: 'spip', label: 'School Improvement Plan'),
      DashboardPage(key: 'curriculum', label: 'Curriculum Tracker'),
      DashboardPage(key: 'calendar', label: 'Academic Calendar'),
      DashboardPage(key: 'hod', label: 'HOD Approvals'),
      DashboardPage(key: 'supplies', label: 'Stationery Requests'),
      DashboardPage(key: 'plc', label: 'PLC Requisitions'),
      DashboardPage(key: 'academic-reports', label: 'Reports & PDF'),
    ],
  ),
  DashboardDef(
    key: 'Admin',
    label: 'Asst. Headmaster (Admin)',
    role: RoleId.asstHeadmasterAdmin,
    pages: [
      DashboardPage(key: 'overview', label: 'Admin Overview'),
      DashboardPage(key: 'approvals', label: 'Approvals'),
      DashboardPage(key: 'compliance', label: 'Compliance Tracker'),
      DashboardPage(key: 'admissions', label: 'Admissions'),
      DashboardPage(key: 'cssps-upload', label: 'CSSPS Placement Upload'),
      DashboardPage(key: 'prospectus', label: 'Prospectus Publishing'),
      DashboardPage(key: 'admissions-config', label: 'Admission Form Config'),
      DashboardPage(key: 'scratch-cards', label: 'Scratch Cards'),
      DashboardPage(key: 'id-cards', label: 'Student ID Cards'),
      DashboardPage(key: 'staff', label: 'Staff Management'),
      DashboardPage(key: 'facilities', label: 'Facilities'),
      DashboardPage(key: 'meetings', label: 'Meetings'),
      DashboardPage(key: 'tasks', label: 'Task Assignments'),
      DashboardPage(key: 'communication', label: 'Communication'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Domestic',
    label: 'Asst. Headmaster (Domestic)',
    role: RoleId.asstHeadmasterDomestic,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'boarding', label: 'Boarding Houses'),
      DashboardPage(key: 'catering', label: 'Catering & Kitchen'),
      DashboardPage(key: 'transport', label: 'Transport'),
      DashboardPage(key: 'cleaning', label: 'Cleaning & Maintenance'),
      DashboardPage(key: 'approvals', label: 'Requisition Approvals'),
      DashboardPage(key: 'compliance', label: 'Compliance'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Bursary',
    label: 'Bursary',
    role: RoleId.bursary,
    pages: [
      DashboardPage(key: 'overview', label: 'Bursary Overview'),
      DashboardPage(key: 'cashbook', label: 'Cash Book'),
      DashboardPage(key: 'studentAccounts', label: 'Student Accounts'),
      DashboardPage(key: 'pettyCash', label: 'Petty Cash'),
      DashboardPage(key: 'imprest', label: 'Imprest Accounts'),
      DashboardPage(key: 'procurement', label: 'Procurement'),
      DashboardPage(key: 'feeding', label: 'Feeding Account'),
      DashboardPage(key: 'boardingSupplies', label: 'Boarding Supplies'),
      DashboardPage(key: 'disbursements', label: 'Disbursements'),
      DashboardPage(key: 'returns', label: 'Daily/Monthly Returns'),
      DashboardPage(key: 'reports', label: 'Bursary Reports'),
    ],
  ),
  DashboardDef(
    key: 'Accountant',
    label: 'Accountant',
    role: RoleId.accountant,
    pages: [
      DashboardPage(key: 'overview', label: 'Financial Overview'),
      DashboardPage(key: 'fees', label: 'Fee / Capitation Ledger'),
      DashboardPage(key: 'invoices', label: 'Invoices'),
      DashboardPage(key: 'payroll', label: 'Payroll'),
      DashboardPage(key: 'expenditure', label: 'Expenditure Log'),
      DashboardPage(key: 'budgetSubmissions', label: 'Budget Submissions'),
      DashboardPage(key: 'budget', label: 'Budget Planner'),
      DashboardPage(key: 'kitchenFinance', label: 'Kitchen Finance'),
      DashboardPage(key: 'returnsApproval', label: 'Returns Approval'),
      DashboardPage(key: 'reports', label: 'Financial Reports'),
    ],
  ),
  DashboardDef(
    key: 'Registry',
    label: 'Registry',
    role: RoleId.registry,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'students', label: 'Student Records'),
      DashboardPage(key: 'admissions', label: 'Admissions'),
      DashboardPage(key: 'certificates', label: 'Certificates & Documents'),
      DashboardPage(key: 'correspondence', label: 'Correspondence Log'),
      DashboardPage(key: 'staff', label: 'Staff Records'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Stores',
    label: 'Stores',
    role: RoleId.stores,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'inventory', label: 'Stock Inventory'),
      DashboardPage(key: 'received', label: 'Goods Received'),
      DashboardPage(key: 'requisition', label: 'Requisitions'),
      DashboardPage(key: 'kitchenIssues', label: 'Kitchen Issues'),
      DashboardPage(key: 'suppliers', label: 'Suppliers'),
      DashboardPage(key: 'audit', label: 'Stock Audit'),
      DashboardPage(key: 'alerts', label: 'Low-Stock Alerts'),
    ],
  ),
  DashboardDef(
    key: 'Security',
    label: 'Security',
    role: RoleId.security,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'gate', label: 'Gate Log'),
      DashboardPage(key: 'exeats', label: 'Exeat Verification'),
      DashboardPage(key: 'incidents', label: 'Incident Reports'),
      DashboardPage(key: 'patrol', label: 'Patrol Schedule'),
      DashboardPage(key: 'visitors', label: 'Visitor Pre-Reg'),
      DashboardPage(key: 'checklist', label: 'Daily Checklist'),
      DashboardPage(key: 'guards', label: 'Guards'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'House',
    label: 'Housemaster',
    role: RoleId.housemaster,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'roster', label: 'House Roster'),
      DashboardPage(key: 'rooms', label: 'Room Allocation'),
      DashboardPage(key: 'rollcall', label: 'Roll Call'),
      DashboardPage(key: 'discipline', label: 'Discipline Log'),
      DashboardPage(key: 'welfare', label: 'Welfare Check'),
      DashboardPage(key: 'exeats', label: 'Exeats'),
      DashboardPage(key: 'requisitions', label: 'Requisitions'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'SeniorHousemaster',
    label: 'Senior Housemaster',
    role: RoleId.seniorHousemaster,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'assignments', label: 'House Assignments'),
      DashboardPage(key: 'approvals', label: 'Requisition Approvals'),
      DashboardPage(key: 'exeats', label: 'Exeat Approvals'),
      DashboardPage(key: 'houses', label: 'Houses'),
      DashboardPage(key: 'rollcall', label: 'Roll Call Summary'),
      DashboardPage(key: 'discipline', label: 'Discipline Log'),
      DashboardPage(key: 'welfare', label: 'Welfare Overview'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Catering',
    label: 'Catering / Kitchen',
    role: RoleId.catering,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'menu', label: 'Menu Planner'),
      DashboardPage(key: 'customMenu', label: 'Special Diet Menus'),
      DashboardPage(key: 'stock', label: 'Kitchen Stock & Issuing'),
      DashboardPage(key: 'requisition', label: 'Food Stock Requisition'),
      DashboardPage(key: 'finance', label: 'Financial Request'),
      DashboardPage(key: 'headcount', label: 'Meal Headcount'),
      DashboardPage(key: 'staff', label: 'Kitchen Staff Roster'),
      DashboardPage(key: 'hygiene', label: 'Hygiene Inspection Log'),
      DashboardPage(key: 'cost', label: 'Food Cost Estimator'),
    ],
  ),
  DashboardDef(
    key: 'Health',
    label: 'Health / Sick Bay',
    role: RoleId.health,
    pages: [
      DashboardPage(key: 'patients', label: 'Patient Log'),
      DashboardPage(key: 'inventory', label: 'Medical Inventory'),
      DashboardPage(key: 'referrals', label: 'Referral Tracker'),
      DashboardPage(key: 'records', label: 'Health Records'),
      DashboardPage(key: 'reports', label: 'Health Reports'),
    ],
  ),
  DashboardDef(
    key: 'Transport',
    label: 'Transport',
    role: RoleId.transport,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'vehicles', label: 'Vehicle Registry'),
      DashboardPage(key: 'trips', label: 'Trip Log'),
      DashboardPage(key: 'maintenance', label: 'Maintenance'),
      DashboardPage(key: 'fuel', label: 'Fuel & Supplies'),
      DashboardPage(key: 'drivers', label: 'Driver Roster'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Cleaning',
    label: 'Cleaning / Labourers',
    role: RoleId.cleaning,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'roster', label: 'Duty Roster'),
      DashboardPage(key: 'tasks', label: 'Task Checklist'),
      DashboardPage(key: 'supplies', label: 'Supply Inventory'),
      DashboardPage(key: 'requisitions', label: 'Supply Requests'),
      DashboardPage(key: 'staff', label: 'Staff Attendance'),
      DashboardPage(key: 'maintenance', label: 'Maintenance Issues'),
      DashboardPage(key: 'inspection', label: 'Inspection Reports'),
    ],
  ),
  DashboardDef(
    key: 'Counselling',
    label: 'Counselling Unit',
    role: RoleId.counselling,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'cases', label: 'Case Log'),
      DashboardPage(key: 'caseDetail', label: 'Case Details'),
      DashboardPage(key: 'appointments', label: 'Appointments'),
      DashboardPage(key: 'referrals', label: 'Referral Tracker'),
      DashboardPage(key: 'career', label: 'Career Resources'),
      DashboardPage(key: 'counsellors', label: 'Our Counsellors'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'LibraryICT',
    label: 'Library & ICT',
    role: RoleId.libraryIct,
    pages: [
      DashboardPage(key: 'catalogue', label: 'Catalogue'),
      DashboardPage(key: 'circulation', label: 'Borrow / Return'),
      DashboardPage(key: 'ict', label: 'ICT Lab Bookings'),
      DashboardPage(key: 'equipment', label: 'Equipment'),
      DashboardPage(key: 'digital', label: 'Digital Resources'),
      DashboardPage(key: 'access', label: 'Access Control'),
      DashboardPage(key: 'requisitions', label: 'Requisitions'),
    ],
  ),
  DashboardDef(
    key: 'SportsClubs',
    label: 'Sports & Clubs',
    role: RoleId.sportsClubs,
    pages: [
      DashboardPage(key: 'clubs', label: 'Clubs & Societies'),
      DashboardPage(key: 'fixtures', label: 'Sports Fixtures'),
      DashboardPage(key: 'participation', label: 'Participation'),
      DashboardPage(key: 'equipment', label: 'Equipment & Kits'),
      DashboardPage(key: 'achievements', label: 'Achievements'),
      DashboardPage(key: 'access', label: 'Access Control'),
      DashboardPage(key: 'requisitions', label: 'Requisitions'),
    ],
  ),
  DashboardDef(
    key: 'PLC',
    label: 'PLC',
    role: RoleId.plc,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'meetings', label: 'Meetings & Attendance'),
      DashboardPage(key: 'duty', label: 'Coordinator Duty Roster'),
      DashboardPage(key: 'observations', label: 'Critical Friend'),
      DashboardPage(key: 'lesson', label: 'Lesson Study Log'),
      DashboardPage(key: 'performance', label: 'Performance Review'),
      DashboardPage(key: 'resources', label: 'Resource Sharing'),
      DashboardPage(key: 'action', label: 'Action Plan Tracker'),
      DashboardPage(key: 'requisitions', label: 'PLC Requisitions'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'SubjectHOD',
    label: 'Subject HOD',
    role: RoleId.subjectHod,
    pages: [
      DashboardPage(key: 'overview', label: 'Department Overview'),
      DashboardPage(key: 'syllabus', label: 'Syllabus Tracker'),
      DashboardPage(key: 'lesson', label: 'Lesson Plan Review'),
      DashboardPage(key: 'exam', label: 'Internal Exam Setting'),
      DashboardPage(key: 'results', label: 'Result Entry'),
    ],
  ),
  DashboardDef(
    key: 'Teacher',
    label: 'Teacher',
    role: RoleId.teacher,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'subjects', label: 'My Subjects & Classes'),
      DashboardPage(key: 'timetable', label: 'My Timetable'),
      DashboardPage(key: 'lessonPlans', label: 'Lesson Plans'),
      DashboardPage(key: 'materials', label: 'Lesson Materials'),
      DashboardPage(key: 'av', label: 'Audio & Video Library'),
      DashboardPage(key: 'live', label: 'Live / Virtual Class'),
      DashboardPage(key: 'assignments', label: 'Assignments & Assessments'),
      DashboardPage(key: 'gradebook', label: 'Gradebook'),
      DashboardPage(key: 'attendance', label: 'Class Attendance'),
      DashboardPage(key: 'roster', label: 'Student Roster'),
      DashboardPage(key: 'syllabus', label: 'Syllabus Tracker'),
      DashboardPage(key: 'remedial', label: 'Remedial Support'),
      DashboardPage(key: 'announcements', label: 'Class Announcements'),
      DashboardPage(key: 'plc', label: 'PLC'),
      DashboardPage(key: 'menu', label: "Today's Menu"),
    ],
  ),
  DashboardDef(
    key: 'Staff',
    label: 'Staff',
    role: RoleId.staff,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'notice', label: 'Staff Notice Board'),
      DashboardPage(key: 'minutes', label: 'Meeting Minutes'),
      DashboardPage(key: 'resources', label: 'Resource Library'),
      DashboardPage(key: 'leave', label: 'Leave Requests'),
      DashboardPage(key: 'directory', label: 'Staff Directory'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'Student',
    label: 'Student',
    role: RoleId.student,
    pages: [
      DashboardPage(key: 'profile', label: 'Profile'),
      DashboardPage(key: 'timetable', label: 'Timetable'),
      DashboardPage(key: 'classes', label: 'My Classes'),
      DashboardPage(key: 'materials', label: 'Learning Materials'),
      DashboardPage(key: 'assignments', label: 'Assignments'),
      DashboardPage(key: 'results', label: 'Results & Report Cards'),
      DashboardPage(key: 'attendance', label: 'Attendance'),
      DashboardPage(key: 'fees', label: 'Fees / Capitation'),
      DashboardPage(key: 'library', label: 'Library Account'),
      DashboardPage(key: 'health', label: 'Health Record'),
      DashboardPage(key: 'elections', label: 'Elections'),
      DashboardPage(key: 'feedback', label: 'Grievance / Feedback'),
    ],
  ),
  DashboardDef(
    key: 'Parent',
    label: 'Parent',
    role: RoleId.parent,
    pages: [
      DashboardPage(key: 'wards', label: 'My Children'),
      DashboardPage(key: 'academic', label: 'Academic Reports'),
      DashboardPage(key: 'attendance', label: 'Attendance'),
      DashboardPage(key: 'exeats', label: 'Exeats'),
      DashboardPage(key: 'discipline', label: 'Discipline & Welfare'),
      DashboardPage(key: 'health', label: 'Health Records'),
      DashboardPage(key: 'announcements', label: 'Announcements'),
      DashboardPage(key: 'meetings', label: 'Meetings & RSVP'),
      DashboardPage(key: 'payments', label: 'Payments'),
      DashboardPage(key: 'fundraising', label: 'Fundraising'),
      DashboardPage(key: 'feedback', label: 'Feedback'),
      DashboardPage(key: 'directory', label: 'Parent Directory'),
    ],
  ),
  DashboardDef(
    key: 'SRC',
    label: 'SRC',
    role: RoleId.src,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'announcements', label: 'Announcements'),
      DashboardPage(key: 'events', label: 'Event Planner'),
      DashboardPage(key: 'grievances', label: 'Grievance Log'),
      DashboardPage(key: 'prefects', label: 'Prefect Roster'),
      DashboardPage(key: 'budget', label: 'Budget Tracker'),
      DashboardPage(key: 'initiatives', label: 'Initiatives'),
      DashboardPage(key: 'feedback', label: 'Student Feedback'),
    ],
  ),
  DashboardDef(
    key: 'ElectoralCommission',
    label: 'Electoral Commission',
    role: RoleId.electoralCommission,
    pages: [
      DashboardPage(key: 'calendar', label: 'Election Calendar'),
      DashboardPage(key: 'candidates', label: 'Candidate Registration'),
      DashboardPage(key: 'voters', label: 'Voter Roll'),
      DashboardPage(key: 'ballot', label: 'Ballot Management'),
      DashboardPage(key: 'voting', label: 'Voting & Live Results'),
      DashboardPage(key: 'reports', label: 'Election Reports'),
      DashboardPage(key: 'settings', label: 'Settings'),
    ],
  ),
  DashboardDef(
    key: 'PTA',
    label: 'PTA',
    role: RoleId.pta,
    pages: [
      DashboardPage(key: 'wards', label: 'My Ward(s)'),
      DashboardPage(key: 'announcements', label: 'Announcements'),
      DashboardPage(key: 'fundraising', label: 'Fundraising'),
      DashboardPage(key: 'meetings', label: 'Meetings'),
      DashboardPage(key: 'directory', label: 'Directory'),
      DashboardPage(key: 'dues', label: 'PTA Dues'),
      DashboardPage(key: 'finance', label: 'Finance'),
      DashboardPage(key: 'feedback', label: 'Feedback'),
      DashboardPage(key: 'access', label: 'Access Control'),
    ],
  ),
  DashboardDef(
    key: 'GoverningBoard',
    label: 'Governing Board',
    role: RoleId.governingBoard,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'policy', label: 'Policy Documents'),
      DashboardPage(key: 'budget', label: 'Budget Approvals'),
      DashboardPage(key: 'minutes', label: 'Meeting Minutes'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'WelfareCommittee',
    label: 'Welfare Committee',
    role: RoleId.welfareCommittee,
    pages: [
      DashboardPage(key: 'ledger', label: 'Welfare Fund Ledger'),
      DashboardPage(key: 'support', label: 'Support Requests'),
      DashboardPage(key: 'disbursement', label: 'Disbursement Approvals'),
      DashboardPage(key: 'membership', label: 'Membership Register'),
    ],
  ),
  DashboardDef(
    key: 'SystemAdmin',
    label: 'System Administrator',
    role: RoleId.systemAdmin,
    pages: [
      DashboardPage(key: 'overview', label: 'System Overview'),
      DashboardPage(key: 'users', label: 'User Management'),
      DashboardPage(key: 'tenant', label: 'School Configuration'),
      DashboardPage(key: 'modules', label: 'Modules'),
      DashboardPage(key: 'database', label: 'Database & Sync'),
      DashboardPage(key: 'backups', label: 'Backups'),
      DashboardPage(key: 'logs', label: 'System Logs'),
    ],
  ),
  DashboardDef(
    key: 'Chaplain',
    label: 'Chaplain',
    role: RoleId.chaplain,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'services', label: 'Service Schedule'),
      DashboardPage(key: 'prayerRequests', label: 'Prayer Requests'),
      DashboardPage(key: 'counselling', label: 'Spiritual Counselling'),
      DashboardPage(key: 'events', label: 'Religious Events'),
      DashboardPage(key: 'fellowships', label: 'Fellowship Groups'),
      DashboardPage(key: 'outreach', label: 'Outreach & Charity'),
      DashboardPage(key: 'choir', label: 'Choir & Music'),
      DashboardPage(key: 'baptism', label: 'Baptism & Dedication'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'AcademicBoard',
    label: 'Academic Board',
    role: RoleId.academicBoard,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'planning', label: 'Academic Planning'),
      DashboardPage(key: 'curriculum', label: 'Curriculum Oversight'),
      DashboardPage(key: 'policy', label: 'Academic Policies'),
      DashboardPage(key: 'departments', label: 'Department Reports'),
      DashboardPage(key: 'assessments', label: 'Assessment Review'),
      DashboardPage(key: 'calendar', label: 'Academic Calendar'),
      DashboardPage(key: 'meetings', label: 'Board Meetings'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'DiningHall',
    label: 'Dining Hall Master',
    role: RoleId.diningHallMaster,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'seating', label: 'Seating Plan'),
      DashboardPage(key: 'menu', label: 'Menu Oversight'),
      DashboardPage(key: 'attendance', label: 'Meal Attendance'),
      DashboardPage(key: 'supplies', label: 'Supplies & Stock'),
      DashboardPage(key: 'hygiene', label: 'Hygiene Inspection'),
      DashboardPage(key: 'feedback', label: 'Student Feedback'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'ExamCommittee',
    label: 'Examination Committee',
    role: RoleId.examCommittee,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'schedule', label: 'Exam Schedule'),
      DashboardPage(key: 'papers', label: 'Question Papers'),
      DashboardPage(key: 'invigilation', label: 'Invigilation Duty'),
      DashboardPage(key: 'grading', label: 'Grading & Moderation'),
      DashboardPage(key: 'results', label: 'Results Processing'),
      DashboardPage(key: 'malpractice', label: 'Malpractice Log'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'SafeSpace',
    label: 'Safe Space',
    role: RoleId.safeSpace,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'incidents', label: 'Safety Incidents'),
      DashboardPage(key: 'inspections', label: 'Safety Inspections'),
      DashboardPage(key: 'relationships', label: 'Relationship Management'),
      DashboardPage(key: 'environment', label: 'Environment Audit'),
      DashboardPage(key: 'training', label: 'Safety Training'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'InternalAuditor',
    label: 'Internal Auditor',
    role: RoleId.internalAuditor,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'audits', label: 'Audit Schedule'),
      DashboardPage(key: 'findings', label: 'Audit Findings'),
      DashboardPage(key: 'compliance', label: 'Compliance Review'),
      DashboardPage(key: 'financial', label: 'Financial Audit'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
  DashboardDef(
    key: 'HeadmasterSecretary',
    label: 'Headmaster Secretary',
    role: RoleId.headmasterSecretary,
    pages: [
      DashboardPage(key: 'overview', label: 'Overview'),
      DashboardPage(key: 'appointments', label: 'Appointments'),
      DashboardPage(key: 'correspondence', label: 'Correspondence'),
      DashboardPage(key: 'filing', label: 'Filing & Records'),
      DashboardPage(key: 'visitors', label: 'Visitor Log'),
      DashboardPage(key: 'tasks', label: 'Task Tracker'),
      DashboardPage(key: 'reports', label: 'Reports'),
    ],
  ),
];

/// Quick lookup map: dashboardKey -> DashboardDef
final Map<String, DashboardDef> dashboardMap = {
  for (final d in dashboardCatalog) d.key: d,
};
